import connectdb from "@/lib/db";
import product from "@/models/product";

export async function GET(){
    await connectdb();
    const products = await product.find();
    await product.deleteMany();

    const randomImageUrl = () =>
      `https://picsum.photos/600/500?random=${Math.floor(Math.random() * 100000)}`;

   
    await product.insertMany([
  {
    title: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    price: 129.99,
    category: "Electronics",
    image: randomImageUrl(),
  },
  {
    title: "Gaming Mouse",
    description: "Ergonomic gaming mouse with customizable RGB lighting.",
    price: 49.99,
    category: "Electronics",
    image: randomImageUrl(),
  },
  {
    title: "Smart Watch",
    description: "Track your fitness and receive notifications on the go.",
    price: 199.99,
    category: "Electronics",
    image: randomImageUrl(),
  },
  {
    title: "Red Shirt",
    description: "Stylish and comfortable cotton shirt.",
    price: 29.99,
    category: "Clothing",
    image: randomImageUrl(),
  },
  {
    title: "Blue Jeans",
    description: "Premium slim-fit denim jeans.",
    price: 59.99,
    category: "Clothing",
    image: randomImageUrl(),
  },
  {
    title: "Running Shoes",
    description: "Lightweight running shoes for everyday training.",
    price: 89.99,
    category: "Footwear",
    image: randomImageUrl(),
  },
  {
    title: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots.",
    price: 24.99,
    category: "Accessories",
    image: randomImageUrl(),
  },
  {
    title: "Backpack",
    description: "Durable backpack with laptop compartment.",
    price: 44.99,
    category: "Accessories",
    image: randomImageUrl(),
  },
  {
    title: "Coffee Maker",
    description: "Brew fresh coffee in minutes.",
    price: 79.99,
    category: "Home & Kitchen",
    image: randomImageUrl(),
  },
  {
    title: "Blender",
    description: "Powerful blender for smoothies and shakes.",
    price: 69.99,
    category: "Home & Kitchen",
    image: randomImageUrl(),
  },
  {
    title: "Air Fryer",
    description: "Healthy cooking with less oil.",
    price: 119.99,
    category: "Home & Kitchen",
    image: randomImageUrl(),
  },
  {
    title: "Desk Lamp",
    description: "LED desk lamp with adjustable brightness.",
    price: 34.99,
    category: "Home Decor",
    image: randomImageUrl(),
  },
{
  title: "Premium Wireless Bluetooth Noise Cancelling Over Ear Headphones with Deep Bass and Long Battery Life",
  description: "High quality wireless bluetooth headphones featuring active noise cancellation, deep bass sound, comfortable ear cushions, long battery life, fast charging, music streaming, gaming, travel, office work and daily entertainment.",
  price: 129.99,
  category: "Electronics",
  image: randomImageUrl(),
},

{
  title: "Professional RGB Mechanical Gaming Keyboard with Blue Switches and Custom Backlighting",
  description: "Mechanical gaming keyboard with RGB lighting, blue switches, anti-ghosting keys, fast response, ergonomic design, gaming setup, esports players, office productivity, coding and programming work.",
  price: 89.99,
  category: "Electronics",
  image: randomImageUrl(),
},

{
  title: "Men's Lightweight Breathable Running Sports Shoes for Gym Workout Walking and Training",
  description: "Comfortable running shoes designed for jogging, walking, gym workout, sports training, fitness activities, outdoor exercise, lightweight cushioning, breathable mesh material and daily casual wear.",
  price: 79.99,
  category: "Footwear",
  image: randomImageUrl(),
},

{
  title: "Premium Genuine Leather Travel Backpack with Laptop Compartment and USB Charging Port",
  description: "Stylish travel backpack featuring laptop compartment, USB charging port, water resistant material, college students, office professionals, business travel, school bag, trekking and daily commuting.",
  price: 69.99,
  category: "Accessories",
  image: randomImageUrl(),
},

{
  title: "Smart Fitness Tracking Watch with Heart Rate Monitor Sleep Tracking and Sports Modes",
  description: "Advanced smart watch with heart rate monitoring, sleep tracking, fitness tracking, calorie counter, bluetooth connectivity, workout modes, running tracker, notifications and health monitoring.",
  price: 199.99,
  category: "Electronics",
  image: randomImageUrl(),
},

{
  title: "Adjustable Ergonomic Office Chair with Lumbar Support and Comfortable Mesh Back Design",
  description: "Ergonomic office chair for work from home setup, study room, gaming desk, lumbar support, adjustable height, comfortable seating, back support, productivity and long working hours.",
  price: 149.99,
  category: "Furniture",
  image: randomImageUrl(),
},

{
  title: "Portable Fast Charging 10000mAh Power Bank with USB Type C and Dual Output Ports",
  description: "High capacity power bank with fast charging support, USB Type C, smartphone charging, travel accessory, portable battery backup, android devices, iPhone charging and emergency power supply.",
  price: 39.99,
  category: "Electronics",
  image: randomImageUrl(),
},

{
  title: "Professional Grade Cricket Bat for Leather Ball Matches Practice Sessions and Tournaments",
  description: "Premium cricket bat suitable for leather ball cricket, practice sessions, professional matches, tournaments, sports training, power hitting, batting performance and cricket enthusiasts.",
  price: 89.99,
  category: "Sports",
  image: randomImageUrl(),
},

{
  title: "Non Stick Premium Cookware Kitchen Set with Frying Pan Saucepan and Cooking Utensils",
  description: "Complete cookware set including frying pan, saucepan, non stick coating, home kitchen essentials, cooking utensils, healthy cooking, easy cleaning and daily meal preparation.",
  price: 99.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},

{
  title: "JavaScript and Modern Full Stack Web Development Complete Programming Guide for Beginners",
  description: "Comprehensive programming book covering JavaScript, React, Next.js, Node.js, MongoDB, frontend development, backend development, coding interview preparation and full stack projects.",
  price: 39.99,
  category: "Books",
  image: randomImageUrl(),
},
{
  title: "Premium Wireless Bluetooth Earbuds with Active Noise Cancellation for Travel Gaming Music and Daily Entertainment",
  description: "High quality wireless bluetooth earbuds featuring active noise cancellation, deep bass audio, crystal clear calling, gaming mode, travel friendly charging case, fitness compatibility, long battery backup and premium sound experience.",
  price: 89.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Professional Mechanical RGB Gaming Keyboard with Hot Swappable Switches and Customizable Backlighting",
  description: "Mechanical gaming keyboard designed for professional gamers, programmers, content creators and office users featuring RGB lighting, anti ghosting technology, ergonomic design and fast response switches.",
  price: 99.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Ultra Lightweight Gaming Mouse with Adjustable DPI RGB Lighting and Ergonomic Grip Design",
  description: "Professional gaming mouse with adjustable DPI settings, customizable RGB lighting, lightweight construction, precision sensor technology, comfortable grip and competitive gaming performance.",
  price: 49.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Smart Fitness Tracking Watch with Heart Rate Monitoring Sleep Analysis and Sports Activity Modes",
  description: "Advanced smart watch offering heart rate tracking, sleep monitoring, fitness goals, calorie counter, running tracker, sports activities, notification support and long battery life.",
  price: 179.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Portable Wireless Bluetooth Speaker with Deep Bass Waterproof Design and Long Battery Backup",
  description: "Portable bluetooth speaker delivering rich audio quality, deep bass performance, waterproof protection, outdoor compatibility, travel convenience and extended battery life.",
  price: 69.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Full HD Professional Webcam with Noise Reduction Microphone for Online Classes and Meetings",
  description: "High definition webcam suitable for online learning, video conferencing, remote work, live streaming, content creation and professional communication.",
  price: 59.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "High Capacity Portable Power Bank with Fast Charging Technology and USB Type C Support",
  description: "Reliable portable power bank featuring fast charging support, multiple device compatibility, smartphone charging, travel convenience and emergency battery backup.",
  price: 44.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Premium External Solid State Drive with High Speed Data Transfer and Portable Design",
  description: "External SSD offering secure storage, fast data transfer speeds, portability, backup solutions, gaming compatibility and professional productivity support.",
  price: 129.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Adjustable Laptop Stand for Improved Ergonomics Work From Home and Office Productivity",
  description: "Aluminum laptop stand designed to improve posture, workspace organization, productivity, cooling performance and professional desk setup.",
  price: 34.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Premium Travel Backpack with Dedicated Laptop Compartment and Water Resistant Material",
  description: "Spacious travel backpack suitable for students, professionals, office workers, travelers and daily commuters with laptop storage and organized compartments.",
  price: 64.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Luxury Genuine Leather Wallet with RFID Protection and Multiple Card Storage Slots",
  description: "Premium leather wallet featuring RFID protection, durable craftsmanship, multiple compartments, modern design and secure everyday carrying experience.",
  price: 39.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "UV Protection Polarized Sunglasses for Outdoor Travel Driving and Sports Activities",
  description: "Stylish polarized sunglasses offering UV protection, comfortable fit, outdoor usability, driving visibility and sports compatibility.",
  price: 29.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Men's Premium Slim Fit Formal Shirt for Office Meetings Business Events and Daily Wear",
  description: "Elegant formal shirt designed for business professionals, office environments, interviews, meetings and sophisticated everyday fashion.",
  price: 49.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Comfortable Cotton Graphic Printed T Shirt for Casual Fashion College and Weekend Wear",
  description: "Breathable cotton t shirt featuring trendy graphics, modern style, casual comfort and all day wearability.",
  price: 24.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Premium Hooded Sweatshirt with Soft Fleece Interior for Winter Comfort and Street Fashion",
  description: "Warm hoodie suitable for winter weather, casual outfits, travel comfort, college students and modern streetwear style.",
  price: 44.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Professional Running Shoes with Breathable Mesh Construction and Advanced Cushioning Technology",
  description: "Lightweight running shoes designed for jogging, gym workouts, marathon training, fitness activities and daily walking comfort.",
  price: 84.99,
  category: "Footwear",
  image: randomImageUrl(),
},
{
  title: "High Performance Basketball Shoes with Ankle Support and Enhanced Court Grip Technology",
  description: "Basketball footwear designed for competitive athletes, sports performance, ankle stability and superior traction.",
  price: 109.99,
  category: "Footwear",
  image: randomImageUrl(),
},
{
  title: "Luxury Memory Foam Office Chair with Adjustable Lumbar Support and Ergonomic Design",
  description: "Ergonomic office chair providing comfort, posture support, productivity enhancement and long working hour convenience.",
  price: 189.99,
  category: "Furniture",
  image: randomImageUrl(),
},
{
  title: "Large Wooden Study Table with Storage Drawers for Students Professionals and Home Offices",
  description: "Spacious study desk suitable for reading, coding, office work, online learning and organized workspace management.",
  price: 219.99,
  category: "Furniture",
  image: randomImageUrl(),
},
{
  title: "Professional Non Stick Cookware Set for Healthy Home Cooking and Kitchen Convenience",
  description: "Complete cookware solution including frying pans, saucepans and cooking essentials for healthy meal preparation.",
  price: 119.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},
{
  title: "Digital Air Fryer with Multiple Cooking Modes for Healthy Oil Free Food Preparation",
  description: "Modern air fryer featuring rapid air circulation, healthy cooking technology, easy controls and versatile meal options.",
  price: 139.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},
{
  title: "Professional Grade Cricket Bat for Match Practice Tournament and Sports Training Sessions",
  description: "Premium cricket bat crafted for performance, durability, power hitting, match practice and competitive tournaments.",
  price: 99.99,
  category: "Sports",
  image: randomImageUrl(),
},
{
  title: "Adjustable Dumbbell Set for Home Gym Strength Training and Fitness Workouts",
  description: "Versatile dumbbell set designed for muscle building, fitness goals, strength training and home exercise routines.",
  price: 89.99,
  category: "Sports",
  image: randomImageUrl(),
},
{
  title: "Complete JavaScript and Full Stack Web Development Guide for Beginners and Professionals",
  description: "Comprehensive programming resource covering JavaScript, React, Next.js, Node.js, MongoDB and modern web development practices.",
  price: 39.99,
  category: "Books",
  image: randomImageUrl(),
},
{
  title: "Advanced Data Structures and Algorithms Interview Preparation Book for Software Engineers",
  description: "Comprehensive DSA guide covering algorithms, coding interviews, competitive programming and software engineering preparation.",
  price: 34.99,
  category: "Books",
  image: randomImageUrl(),
},
{
  title: "Premium Wireless Noise Cancelling Over Ear Headphones with Deep Bass Audio and Long Battery Life",
  description: "High quality wireless headphones with active noise cancellation, immersive deep bass sound, travel comfort, gaming compatibility, office use, music streaming, online classes and all day battery backup.",
  price: 149.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Ultra Wide Full HD Gaming Monitor with High Refresh Rate and Eye Comfort Technology",
  description: "Professional gaming monitor featuring high refresh rate, low latency, eye protection mode, immersive display quality, content creation support and productivity enhancement.",
  price: 249.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Professional USB Condenser Microphone for Podcasting Streaming Recording and Content Creation",
  description: "Studio quality microphone designed for podcasters, streamers, content creators, online teaching, gaming communication and professional voice recording.",
  price: 89.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Smart Home Security Camera with Motion Detection Night Vision and Mobile App Access",
  description: "Advanced home security camera offering motion alerts, night vision technology, smartphone connectivity, remote monitoring and family safety features.",
  price: 99.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Portable Wireless Charging Station for Smartphones Smart Watches and Bluetooth Earbuds",
  description: "Multi device wireless charging station designed for smartphones, smart watches, earbuds, office desks, travel convenience and clutter free organization.",
  price: 59.99,
  category: "Electronics",
  image: randomImageUrl(),
},
{
  title: "Men's Premium Stretchable Slim Fit Blue Denim Jeans for Casual and Everyday Fashion",
  description: "Comfortable slim fit denim jeans featuring stretchable fabric, modern styling, casual wear versatility, travel comfort and long lasting durability.",
  price: 54.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Luxury Winter Jacket with Water Resistant Exterior and Thermal Insulation Technology",
  description: "Premium winter jacket offering warmth, weather protection, travel convenience, outdoor comfort and stylish cold season fashion.",
  price: 119.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Professional Business Suit Blazer for Corporate Meetings Formal Events and Interviews",
  description: "Elegant business blazer suitable for professionals, interviews, office meetings, corporate events and formal occasions.",
  price: 129.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Comfortable Athletic Joggers for Gym Workouts Running Training and Casual Lifestyle",
  description: "Breathable athletic joggers designed for fitness enthusiasts, gym sessions, sports activities, jogging and daily casual wear.",
  price: 34.99,
  category: "Clothing",
  image: randomImageUrl(),
},
{
  title: "Men's Premium Leather Formal Shoes with Cushioning Comfort and Elegant Office Styling",
  description: "Luxury formal shoes designed for office professionals, business meetings, weddings, corporate events and daily comfort.",
  price: 99.99,
  category: "Footwear",
  image: randomImageUrl(),
},
{
  title: "Lightweight Casual Sneakers with Breathable Design for Travel Walking and Everyday Comfort",
  description: "Modern sneakers featuring breathable materials, travel convenience, walking support, casual fashion and all day comfort.",
  price: 69.99,
  category: "Footwear",
  image: randomImageUrl(),
},
{
  title: "Professional Hiking Boots with Waterproof Protection and Rugged Outdoor Performance",
  description: "Durable hiking boots suitable for trekking, camping, outdoor adventures, mountain exploration and rough terrain walking.",
  price: 139.99,
  category: "Footwear",
  image: randomImageUrl(),
},
{
  title: "Premium Smart Travel Luggage Bag with TSA Lock and Expandable Storage Capacity",
  description: "Travel luggage featuring TSA security lock, spacious compartments, durable construction, smooth wheels and international travel convenience.",
  price: 159.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Professional Laptop Messenger Bag with Water Resistant Material and Organized Compartments",
  description: "Business messenger bag designed for office professionals, students, daily commuters, laptop storage and travel convenience.",
  price: 49.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Premium Stainless Steel Vacuum Insulated Water Bottle for Gym Travel and Outdoor Sports",
  description: "High quality insulated bottle maintaining beverage temperature, suitable for fitness, travel, sports activities and daily hydration.",
  price: 24.99,
  category: "Accessories",
  image: randomImageUrl(),
},
{
  title: "Digital Coffee Maker with Programmable Brewing Features and Premium Aroma Extraction",
  description: "Modern coffee machine offering programmable brewing, rich coffee flavor, convenience, office use and home kitchen excellence.",
  price: 109.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},
{
  title: "Premium Electric Kettle with Fast Boiling Technology and Automatic Safety Shut Off",
  description: "Efficient electric kettle designed for tea preparation, coffee making, quick boiling and modern kitchen convenience.",
  price: 44.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},
{
  title: "Large Capacity Refrigerator Storage Organizer Set for Kitchen and Food Management",
  description: "Practical storage solution helping organize fruits, vegetables, beverages and kitchen essentials efficiently.",
  price: 29.99,
  category: "Home & Kitchen",
  image: randomImageUrl(),
},
{
  title: "Professional Yoga Mat with Non Slip Surface for Fitness Training Meditation and Exercise",
  description: "Premium yoga mat offering comfort, stability, flexibility support, home workouts, meditation practice and fitness routines.",
  price: 39.99,
  category: "Sports",
  image: randomImageUrl(),
},
{
  title: "Professional Football Training Kit with Durable Ball Cones and Practice Equipment",
  description: "Complete football training equipment suitable for athletes, sports academies, practice drills and fitness improvement.",
  price: 59.99,
  category: "Sports",
  image: randomImageUrl(),
},
{
  title: "Adjustable Resistance Bands Set for Home Gym Strength Training and Muscle Building",
  description: "Versatile resistance bands designed for strength training, flexibility improvement, rehabilitation and fitness workouts.",
  price: 29.99,
  category: "Sports",
  image: randomImageUrl(),
},
{
  title: "Comprehensive Python Programming and Machine Learning Development Guide for Beginners",
  description: "Detailed programming book covering Python fundamentals, machine learning concepts, data science, AI development and practical projects.",
  price: 42.99,
  category: "Books",
  image: randomImageUrl(),
},
{
  title: "Modern Artificial Intelligence and Deep Learning Concepts with Real World Applications",
  description: "Educational AI book covering neural networks, deep learning, machine learning algorithms and practical implementation strategies.",
  price: 49.99,
  category: "Books",
  image: randomImageUrl(),
},
{
  title: "Professional Hair Styling Kit with Hair Dryer Straightener and Multiple Accessories",
  description: "Complete beauty kit designed for hair styling, grooming, salon quality results and personal care routines.",
  price: 89.99,
  category: "Beauty",
  image: randomImageUrl(),
},
{
  title: "Luxury Long Lasting Perfume with Premium Fragrance Notes for Daily and Special Occasions",
  description: "Elegant perfume featuring long lasting fragrance, premium ingredients, sophisticated aroma and versatile everyday usage.",
  price: 59.99,
  category: "Beauty",
  image: randomImageUrl(),
},
])
return Response.json({message : "Database seeded successfully"})
}
    

